[Impressora]
; Porta serial da impressora termica nesta maquina
; Expedicao: geralmente COM3
; Entrega:   geralmente COM4
Porta=COM3
; BaudRate: Bematech_MP4200TH=115200 | ElginI9=9600 (ou 115200 conforme config)
BaudRate=9600
Colunas=48
; Modelo: Bematech_MP4200TH | ElginI9
Modelo=ElginI9
